version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/docs" ]
      timeout: 3s
      retries: 3
    depends_on:
      - db
  migration:
    build: .
    command: alembic upgrade head
    environment:
      - POSTGRES_SERVER=db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=realworld
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
  nginx:
    image: nginx:stable-alpine
    container_name: realworld-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - app

volumes:
  app-db-data:
